Added start command for running seamlessly from docker
reswitched/pegaswitch pull request #33
Opened 2017-10-03 04:34 UTC by JoelLarson

This command will allow anyone with docker to easily build pegaswitch without needing the nodejs requirement on their local machine.

It will also have the added benefit of allowing pegaswitch to easily run on any platform without hassle.

Let me know if there's any feedback or improvements if this can get in!

2017-10-03 04:41 UTC, SomeoneWeird requested changes
Should probably also add a `start-docker` command or something in package.json and add it to the readme too.

2017-10-03 04:41 UTC, SomeoneWeird commented on bin/start.sh
> +    echo "Docker must be installed to use this feature. Exiting..." >&2
You don't actually exit here?

2017-10-03 04:47 UTC, JoelLarson commented
@SomeoneWeird Thanks for the feedback! I made all the changes for it. I'm about to add a executable file for windows as well that I'm testing on another machine.

2017-10-03 05:23 UTC, misson20000 commented
Can we pass through arguments to start.js? I almost never use the defaults.

2017-10-03 05:34 UTC, JoelLarson commented
@misson20000 I added an argument passthrough for it.

`./bin/start-docker.sh --ip 1.2.3.4` should work as expected.

2017-10-03 05:36 UTC, SomeoneWeird commented on bin/start-docker.sh
> +exit 0
I don't think you want this :)

2017-10-03 05:37 UTC, JoelLarson commented on bin/start-docker.sh
> +exit 0
Debug code... lol

2017-10-03 05:39 UTC, JoelLarson commented
It's now removed

2017-10-03 05:41 UTC, JoelLarson commented
I'm having some npm install issues with the version on windows so I think I'll make a pull request for that in the future. This one can be marked done if there isn't anything else lingering.

2017-10-04 03:51 UTC, JoelLarson commented
@SomeoneWeird I have added Windows support! It is now as simple as double clicking the bat file.

2017-10-04 05:38 UTC, misson20000 commented on README.md
> +You can find the latest version of documentation hosted [here](https://reswitched.github.io/PegaSwitch/)
This link is case sensitive

2017-10-04 05:48 UTC, misson20000 commented
This does not seem to be passing arguments to pegaswitch properly. This is my usual command line:
```
$ sudo node start.js --disable-curses --logfile log.txt --ip 10.0.0.192 --setuid misson20000
```
When I run this,
```
$ bin/start-docker.sh --disable-curses --logfile log.txt --ip 10.0.0.192 --setuid misson20000
```
PegaSwitch still opens the curses interface and reports that
```
DNS Server started, responding with address 172.17.0.2
```

2017-10-04 13:57 UTC, JoelLarson commented
@misson20000 I have fixed that bug now. I accidentally used single quotes instead of double quotes while I was trying to fix something else.

2017-10-05 10:01 UTC, meeces2911 commented
Also, to add to that, you might want to specify port 53 as UDP in the docker port bind.

2017-10-05 14:20 UTC, JoelLarson commented
Thanks @meeces2911! Just fixed both problems. I'll test them when I get home tonight.

2017-10-06 06:47 UTC, JoelLarson commented
- [x] Tested running `./bin/start-docker.bat` on Windows by double clicking.
- [x] Tested running `./bin/start-docker.bat --ip 1.2.3.4` on Windows.
- [x] Tested `./bin/start-docker.sh` runs from root path.
- [x] Tested `./bin/start-docker.sh --disable-curses --logfile log.txt --ip 10.0.0.192`
- [x] Tested `npm run-script start-docker`
- [x] Tested `npm run-script start-docker -- --disable-curses --logfile log.txt --ip 10.0.0.192`
- [x] Tested that DNS port was open (`53/udp`)
- [x] Tested that HTTP port was open (`80/tcp`)
- [] Tested that WebSocket port was open and correct (`8100/tcp`)

DNS Test
`dig @localhost -p 53 foo.example A` should confirm what `--ip` is set to.

Web Test
`curl --silent -X GET http://localhost/ | grep -q -i 'PegaSwitch' && echo 'Serving PegaSwitch.' || echo 'PegaSwitch is not being served correctly.'`

I'm not sure how to test port 8100 (the websocket) since I think it mounts only when the program is running and I do not have a Switch with a compatible OS.

2017-10-13 21:07 UTC, JoelLarson commented
@SomeoneWeird Is anything left for this?

2021-01-24 06:16 UTC, closed without merging